### ISSUE TITLE
Support Quadro Cards

### ISSUE THREAD

**Issue by ErikParawell-SiFive** [fancyIX/ccminer#16]
You said to open a issue to support Quadro Cards.

Is there a way I can try fixing it myself? I've played around with CUDA a bit, but the biggest thing I've done is write an image scaler so I don't have much experience or a deep understanding.

**Comment by fancyIX** [comment]
Also support RTX A5000 etc

**Comment by ErikParawell-SiFive** [comment]
In particular I have a Quadro T600

**Comment by fancyIX** [comment]
@ErikParawell-SiFive seems like Quadro T600 is Turning arch, while RTX 30xx cards are Ampere arch. The new version (0.4.0) only works for ampere arch. So your GPU won't be imporoved in any case.
