### ISSUE TITLE
Support 0x10

### ISSUE THREAD

**Issue by fancyIX** [fancyIX/ccminer#18]
https://github.com/chainox-official/chainox-ccminer

**Comment by fancyIX** [comment]
https://github.com/Kudaraidee/ccminer-chainox

**Comment by lamgztey** [comment]
![image](https://user-images.githubusercontent.com/32880928/158012462-3888c555-5441-406f-9e6d-c272c3a54441.png)

**Comment by lamgztey** [comment]
![image](https://user-images.githubusercontent.com/32880928/158012763-26b73f92-d480-4b45-8a08-1cb7821320f5.png)

**Comment by fancyIX** [comment]
Seems like grostl hash function can be improved.
https://github.com/KlausT/ccminer/blob/7170593b8e6597feabef493a07ec7c5bf1617227/cuda_groestlcoin.cu

**Comment by lamgztey** [comment]
Help me ! cannot run on HiveOS !

**Comment by fancyIX** [comment]
https://github.com/sp-hash/suprminer/tree/master/x11

**Comment by BuboniK666** [comment]
thanks:i:see:
